<?php
// +----------------------------------------------------------------------
// | ThinkPHP [ WE CAN DO IT JUST THINK ]
// +----------------------------------------------------------------------
// | Copyright (c) 2006~2016 http://thinkphp.cn All rights reserved.
// +----------------------------------------------------------------------
// | Licensed ( http://www.apache.org/licenses/LICENSE-2.0 )
// +----------------------------------------------------------------------
// | Author: liu21st <liu21st@gmail.com>
// +----------------------------------------------------------------------
return [
    //easyui生成表格 需要格式
    '_colums' => [
        'user'          => [
            ['title' => '姓名', 'field' => 'name', 'width' => '100', 'align' => 'center'],
            ['title' => '所属部门', 'field' => 'dept', 'width' => '120', 'align' => 'center'],
            ['title' => '创建时间', 'field' => 'create_time', 'width' => '220', 'align' => 'center'],
            ['title' => '修改时间', 'field' => 'update_time', 'width' => '220', 'align' => 'center'],
            ['title' => '操作', 'field' => 'n21', 'width' => '220', 'align' => 'center', 'formatter' => ''],
            ['title' => 'id', 'field' => 'id', 'width' => '100', 'align' => 'center', 'hidden' => true],
            ['title' => 'rules', 'field' => 'rules', 'width' => '100', 'align' => 'center', 'hidden' => true],
        ],
        'behaviour'     => [
            ['title' => '日期', 'field' => 'date', 'width' => '100', 'align' => 'center'],
            ['title' => '注册会员数', 'field' => 'register', 'width' => '120', 'align' => 'center'],
            ['title' => '活跃会员数', 'field' => 'active', 'width' => '120', 'align' => 'center'],
            ['title' => '独立访客', 'field' => 'uv', 'width' => '120', 'align' => 'center'],
            ['title' => '首页浏览量', 'field' => 'home_in', 'width' => '120', 'align' => 'center'],
            ['title' => '首页跳出率', 'field' => 'home_out', 'width' => '120', 'align' => 'center'],
        ],
        'order'         => [
            ['title' => '日期', 'field' => 'date', 'width' => '100', 'align' => 'center'],
            ['title' => '下单时间', 'field' => 'create_time', 'width' => '120', 'align' => 'center'],
            ['title' => '商品ID', 'field' => 'pid', 'width' => '120', 'align' => 'center'],
            ['title' => '商品名称', 'field' => 'pname', 'width' => '120', 'align' => 'center'],
            ['title' => '用户ID', 'field' => 'uid', 'width' => '120', 'align' => 'center'],
            ['title' => '商品单价', 'field' => 'unit', 'width' => '120', 'align' => 'center'],
            ['title' => '成本价', 'field' => 'cost', 'width' => '120', 'align' => 'center'],
            ['title' => '购买数量', 'field' => 'buy_num', 'width' => '120', 'align' => 'center'],
            ['title' => '订单总额', 'field' => 'order_num', 'width' => '120', 'align' => 'center'],
            ['title' => '订单状态', 'field' => 'status', 'width' => '120', 'align' => 'center'],
        ],
        'visit'         => [
            ['title' => '日期', 'field' => 'date', 'width' => '100', 'align' => 'center'],
            ['title' => '访问量', 'field' => 'num', 'width' => '120', 'align' => 'center'],
            ['title' => '平均会话时长', 'field' => 'length', 'width' => '120', 'align' => 'center'],
            ['title' => '页面链接', 'field' => 'url', 'width' => '600', 'align' => 'left'],
        ],
        'feature'       => [
            [
                ['title' => '日期', 'field' => 'date', 'width' => '100', 'align' => 'center', 'rowspan' => 2],
                ['title' => '登录比例', 'field' => '', 'colspan' => 2],
                ['title' => '性别', 'field' => '', 'colspan' => 2],
                ['title' => '年龄', 'field' => '', 'colspan' => 5],
            ],
            [
                ['title' => '登录用户比例', 'field' => 'login', 'width' => '120', 'align' => 'center'],
                ['title' => '未登录用户比例', 'field' => 'nologin', 'width' => '120', 'align' => 'center'],
                ['title' => '男性比例', 'field' => 'man', 'width' => '120', 'align' => 'center'],
                ['title' => '女性比例', 'field' => 'woman', 'width' => '120', 'align' => 'center'],
                ['title' => '18以下比例', 'field' => 'age18', 'width' => '120', 'align' => 'center'],
                ['title' => '18-24比例', 'field' => 'age24', 'width' => '120', 'align' => 'center'],
                ['title' => '25-34比例', 'field' => 'age34', 'width' => '120', 'align' => 'center'],
                ['title' => '35-44比例', 'field' => 'age44', 'width' => '120', 'align' => 'center'],
                ['title' => '45-比例', 'field' => 'age', 'width' => '120', 'align' => 'center'],
            ],
        ],
        'area'          => [
            ['title' => '日期', 'field' => 'date', 'width' => '100', 'align' => 'center'],
            ['title' => '江苏', 'field' => 'js', 'width' => '120', 'align' => 'center'],
            ['title' => '北京', 'field' => 'bj', 'width' => '120', 'align' => 'center'],
            ['title' => '广东', 'field' => 'gd', 'width' => '120', 'align' => 'center'],
            ['title' => '安徽', 'field' => 'ah', 'width' => '120', 'align' => 'center'],
            ['title' => '四川', 'field' => 'sc', 'width' => '120', 'align' => 'center'],
            ['title' => '浙江', 'field' => 'zj', 'width' => '120', 'align' => 'center'],
            ['title' => '湖北', 'field' => 'hb1', 'width' => '120', 'align' => 'center'],
            ['title' => '吉林', 'field' => 'jl', 'width' => '120', 'align' => 'center'],
            ['title' => '河南', 'field' => 'hn', 'width' => '120', 'align' => 'center'],
            ['title' => '山东', 'field' => 'sd', 'width' => '120', 'align' => 'center'],
            ['title' => '河北', 'field' => 'hb2', 'width' => '120', 'align' => 'center'],
            ['title' => '上海', 'field' => 'sh', 'width' => '120', 'align' => 'center'],
            ['title' => '江西', 'field' => 'jx', 'width' => '120', 'align' => 'center'],
            ['title' => '辽宁', 'field' => 'ln', 'width' => '120', 'align' => 'center'],
            ['title' => '陕西', 'field' => 'sx', 'width' => '120', 'align' => 'center'],
            ['title' => '福建', 'field' => 'fj', 'width' => '120', 'align' => 'center'],
            ['title' => '黑龙江', 'field' => 'hlj', 'width' => '120', 'align' => 'center'],
        ],
        'data'          => [
            ['title' => '日期', 'field' => 'date', 'width' => '100', 'align' => 'center'],
            ['title' => 'UV', 'field' => 'uv', 'width' => '120', 'align' => 'center'],
            ['title' => '登录用户数', 'field' => 'login_num', 'width' => '120', 'align' => 'center'],
            ['title' => '发帖数', 'field' => 'num', 'width' => '120', 'align' => 'center'],
            ['title' => 'PV', 'field' => 'pv', 'width' => '120', 'align' => 'center'],
        ],
        'interest'      => [
            ['title' => '日期', 'field' => 'date', 'width' => '100', 'align' => 'center'],
            ['title' => '影视音乐', 'field' => 'music', 'width' => '120', 'align' => 'center'],
            ['title' => '书籍阅读', 'field' => 'book', 'width' => '120', 'align' => 'center'],
            ['title' => '游戏', 'field' => 'game', 'width' => '120', 'align' => 'center'],
            ['title' => '个护美容', 'field' => 'beauty', 'width' => '120', 'align' => 'center'],
            ['title' => '体育健身', 'field' => 'sports', 'width' => '120', 'align' => 'center'],
            ['title' => '教育培训', 'field' => 'education', 'width' => '120', 'align' => 'center'],
            ['title' => '家电数码', 'field' => 'numeral', 'width' => '120', 'align' => 'center'],
            ['title' => '资讯', 'field' => 'news', 'width' => '120', 'align' => 'center'],
            ['title' => '医疗健康', 'field' => 'health', 'width' => '120', 'align' => 'center'],
            ['title' => '软件应用', 'field' => 'software', 'width' => '120', 'align' => 'center'],
            ['title' => '网络购物', 'field' => 'internet', 'width' => '120', 'align' => 'center'],
            ['title' => '花鸟萌宠', 'field' => 'pet', 'width' => '120', 'align' => 'center'],
            ['title' => '餐饮美食', 'field' => 'eat', 'width' => '120', 'align' => 'center'],
            ['title' => '休闲爱好', 'field' => 'play', 'width' => '120', 'align' => 'center'],
            ['title' => '休闲娱乐', 'field' => 'play1', 'width' => '120', 'align' => 'center'],
            ['title' => '汽车', 'field' => 'car', 'width' => '120', 'align' => 'center'],
            ['title' => '求职创业', 'field' => 'qzcy', 'width' => '120', 'align' => 'center'],
        ],
        'collect'       => [
            ['title' => '日期', 'field' => 'date', 'width' => '100', 'align' => 'center'],
            ['title' => '访问用户', 'field' => 'active', 'width' => '120', 'align' => 'center'],
            ['title' => '客户端访问数', 'field' => 'visit', 'width' => '120', 'align' => 'center'],
            ['title' => '主题数', 'field' => 'theme', 'width' => '120', 'align' => 'center'],
            ['title' => '客户端主题数', 'field' => 'pc_theme', 'width' => '120', 'align' => 'center'],
            ['title' => '回复数', 'field' => 'reply', 'width' => '120', 'align' => 'center'],
            ['title' => '客户端回复数', 'field' => 'pc_reply', 'width' => '120', 'align' => 'center'],
            ['title' => '签到数', 'field' => 'signin', 'width' => '120', 'align' => 'center'],
            ['title' => '客户端签到数', 'field' => 'pc_signin', 'width' => '120', 'align' => 'center'],
            ['title' => '签到率', 'field' => 'signin_ratio', 'width' => '120', 'align' => 'center'],
            ['title' => '新增会员数', 'field' => 'new_member', 'width' => '120', 'align' => 'center'],
            ['title' => '总会员数', 'field' => 'total_member', 'width' => '120', 'align' => 'center'],
        ],
        'step'          => [
            [
                ['title' => '日期', 'field' => 'date', 'width' => '100', 'align' => 'center', 'rowspan' => 2],
                ['title' => '步长分布', 'field' => '', 'colspan' => 5],
            ],
            [
                ['title' => '1', 'field' => 'n1', 'width' => '120', 'align' => 'center'],
                ['title' => '2~5', 'field' => 'n2', 'width' => '120', 'align' => 'center'],
                ['title' => '6~20', 'field' => 'n6', 'width' => '120', 'align' => 'center'],
                ['title' => '21~50', 'field' => 'n21', 'width' => '120', 'align' => 'center'],
                ['title' => '50+', 'field' => 'n50', 'width' => '120', 'align' => 'center'],
            ],
        ],
        'ffrom'         => [
            [
                ['title' => '日期', 'field' => 'date', 'width' => '100', 'align' => 'center', 'rowspan' => 2],
                ['title' => '贴吧', 'field' => '', 'colspan' => 3],
                ['title' => '安卓', 'field' => '', 'colspan' => 3],
                ['title' => 'ios', 'field' => '', 'colspan' => 3],
                ['title' => '主动访问', 'field' => '', 'colspan' => 3],
                ['title' => '其他', 'field' => '', 'colspan' => 3],
                ['title' => 'PS', 'field' => '', 'colspan' => 3],
                ['title' => '阿拉丁', 'field' => '', 'colspan' => 3],
                ['title' => '外部PS', 'field' => '', 'colspan' => 3],
                ['title' => 'Tab页', 'field' => '', 'colspan' => 3],
                ['title' => 'pad页', 'field' => '', 'colspan' => 3],
                ['title' => '导航站', 'field' => '', 'colspan' => 3],
            ],
            [
                ['title' => 'UV', 'field' => 'tb_1', 'width' => '120', 'align' => 'center'],
                ['title' => '人均PV', 'field' => 'tb_2', 'width' => '120', 'align' => 'center'],
                ['title' => '占比', 'field' => 'tb_3', 'width' => '120', 'align' => 'center'],
                ['title' => 'UV', 'field' => 'az_1', 'width' => '120', 'align' => 'center'],
                ['title' => '人均PV', 'field' => 'az_2', 'width' => '120', 'align' => 'center'],
                ['title' => '占比', 'field' => 'az_3', 'width' => '120', 'align' => 'center'],
                ['title' => 'UV', 'field' => 'ios_1', 'width' => '120', 'align' => 'center'],
                ['title' => '人均PV', 'field' => 'ios_2', 'width' => '120', 'align' => 'center'],
                ['title' => '占比', 'field' => 'ios_3', 'width' => '120', 'align' => 'center'],
                ['title' => 'UV', 'field' => 'zd_1', 'width' => '120', 'align' => 'center'],
                ['title' => '人均PV', 'field' => 'zd_2', 'width' => '120', 'align' => 'center'],
                ['title' => '占比', 'field' => 'zd_3', 'width' => '120', 'align' => 'center'],
                ['title' => 'UV', 'field' => 'qt_1', 'width' => '120', 'align' => 'center'],
                ['title' => '人均PV', 'field' => 'qt_2', 'width' => '120', 'align' => 'center'],
                ['title' => '占比', 'field' => 'qt_3', 'width' => '120', 'align' => 'center'],
                ['title' => 'UV', 'field' => 'ps_1', 'width' => '120', 'align' => 'center'],
                ['title' => '人均PV', 'field' => 'ps_2', 'width' => '120', 'align' => 'center'],
                ['title' => '占比', 'field' => 'ps_3', 'width' => '120', 'align' => 'center'],
                ['title' => 'UV', 'field' => 'ald_1', 'width' => '120', 'align' => 'center'],
                ['title' => '人均PV', 'field' => 'ald_2', 'width' => '120', 'align' => 'center'],
                ['title' => '占比', 'field' => 'ald_3', 'width' => '120', 'align' => 'center'],
                ['title' => 'UV', 'field' => 'wbps_1', 'width' => '120', 'align' => 'center'],
                ['title' => '人均PV', 'field' => 'wbps_2', 'width' => '120', 'align' => 'center'],
                ['title' => '占比', 'field' => 'wbps_3', 'width' => '120', 'align' => 'center'],
                ['title' => 'UV', 'field' => 'tab_1', 'width' => '120', 'align' => 'center'],
                ['title' => '人均PV', 'field' => 'tab_2', 'width' => '120', 'align' => 'center'],
                ['title' => '占比', 'field' => 'tab_3', 'width' => '120', 'align' => 'center'],
                ['title' => 'UV', 'field' => 'tab1_1', 'width' => '120', 'align' => 'center'],
                ['title' => '人均PV', 'field' => 'tab1_2', 'width' => '120', 'align' => 'center'],
                ['title' => '占比', 'field' => 'tab1_3', 'width' => '120', 'align' => 'center'],
                ['title' => 'UV', 'field' => 'tab2_1', 'width' => '120', 'align' => 'center'],
                ['title' => '人均PV', 'field' => 'tab2_2', 'width' => '120', 'align' => 'center'],
                ['title' => '占比', 'field' => 'tab2_3', 'width' => '120', 'align' => 'center'],
            ],
        ],
        'iin'           => [
            ['title' => '日期', 'field' => 'date', 'width' => '100', 'align' => 'center'],
            ['title' => '吧名称', 'field' => 'name', 'width' => '120', 'align' => 'center'],
            ['title' => '用户数', 'field' => 'num', 'width' => '120', 'align' => 'center'],
            ['title' => '吧名称', 'field' => 'name1', 'width' => '120', 'align' => 'center'],
            ['title' => '用户数', 'field' => 'num1', 'width' => '120', 'align' => 'center'],
            ['title' => '吧名称', 'field' => 'name2', 'width' => '120', 'align' => 'center'],
            ['title' => '用户数', 'field' => 'num2', 'width' => '120', 'align' => 'center'],
            ['title' => '吧名称', 'field' => 'name3', 'width' => '120', 'align' => 'center'],
            ['title' => '用户数', 'field' => 'num3', 'width' => '120', 'align' => 'center'],
            ['title' => '吧名称', 'field' => 'name4', 'width' => '120', 'align' => 'center'],
            ['title' => '用户数', 'field' => 'num4', 'width' => '120', 'align' => 'center'],
        ],
        'oout'          => [
            ['title' => '日期', 'field' => 'date', 'width' => '100', 'align' => 'center'],
            ['title' => '吧名称', 'field' => 'name', 'width' => '120', 'align' => 'center'],
            ['title' => '用户数', 'field' => 'num', 'width' => '120', 'align' => 'center'],
            ['title' => '吧名称', 'field' => 'name1', 'width' => '120', 'align' => 'center'],
            ['title' => '用户数', 'field' => 'num1', 'width' => '120', 'align' => 'center'],
            ['title' => '吧名称', 'field' => 'name2', 'width' => '120', 'align' => 'center'],
            ['title' => '用户数', 'field' => 'num2', 'width' => '120', 'align' => 'center'],
            ['title' => '吧名称', 'field' => 'name3', 'width' => '120', 'align' => 'center'],
            ['title' => '用户数', 'field' => 'num3', 'width' => '120', 'align' => 'center'],
            ['title' => '吧名称', 'field' => 'name4', 'width' => '120', 'align' => 'center'],
            ['title' => '用户数', 'field' => 'num4', 'width' => '120', 'align' => 'center'],
        ],
        'ttime'         => [
            ['title' => '日期', 'field' => 'date', 'width' => '100', 'align' => 'center'],
            ['title' => '0', 'field' => 't0', 'width' => '40', 'align' => 'center'],
            ['title' => '1', 'field' => 't1', 'width' => '40', 'align' => 'center'],
            ['title' => '2', 'field' => 't2', 'width' => '40', 'align' => 'center'],
            ['title' => '3', 'field' => 't3', 'width' => '40', 'align' => 'center'],
            ['title' => '4', 'field' => 't4', 'width' => '40', 'align' => 'center'],
            ['title' => '5', 'field' => 't5', 'width' => '40', 'align' => 'center'],
            ['title' => '6', 'field' => 't6', 'width' => '40', 'align' => 'center'],
            ['title' => '7', 'field' => 't7', 'width' => '40', 'align' => 'center'],
            ['title' => '8', 'field' => 't8', 'width' => '40', 'align' => 'center'],
            ['title' => '9', 'field' => 't9', 'width' => '40', 'align' => 'center'],
            ['title' => '10', 'field' => 't10', 'width' => '40', 'align' => 'center'],
            ['title' => '11', 'field' => 't11', 'width' => '40', 'align' => 'center'],
            ['title' => '12', 'field' => 't12', 'width' => '40', 'align' => 'center'],
            ['title' => '13', 'field' => 't13', 'width' => '40', 'align' => 'center'],
            ['title' => '14', 'field' => 't14', 'width' => '40', 'align' => 'center'],
            ['title' => '15', 'field' => 't15', 'width' => '40', 'align' => 'center'],
            ['title' => '16', 'field' => 't16', 'width' => '40', 'align' => 'center'],
            ['title' => '17', 'field' => 't17', 'width' => '40', 'align' => 'center'],
            ['title' => '18', 'field' => 't18', 'width' => '40', 'align' => 'center'],
            ['title' => '19', 'field' => 't19', 'width' => '40', 'align' => 'center'],
            ['title' => '20', 'field' => 't20', 'width' => '40', 'align' => 'center'],
            ['title' => '21', 'field' => 't21', 'width' => '40', 'align' => 'center'],
            ['title' => '22', 'field' => 't22', 'width' => '40', 'align' => 'center'],
            ['title' => '23', 'field' => 't23', 'width' => '40', 'align' => 'center'],
        ],
        'behaviourInfo' => [
            [
                ['title' => '日期', 'field' => 'date', 'width' => '100', 'align' => 'center', 'rowspan' => 2],
                ['title' => '活跃', 'field' => '', 'colspan' => 5],
                ['title' => '人均PV', 'field' => '', 'colspan' => 3],
                ['title' => '人均发帖', 'field' => '', 'colspan' => 3],
            ],
            [
                ['title' => '发主题者', 'field' => 'send_active', 'width' => '120', 'align' => 'center'],
                ['title' => '仅回复者', 'field' => 'reply_active', 'width' => '120', 'align' => 'center'],
                ['title' => '围观者', 'field' => 'see_active', 'width' => '120', 'align' => 'center'],
                ['title' => '访问人数', 'field' => 'visit', 'width' => '120', 'align' => 'center'],
                ['title' => '活跃度', 'field' => 'active_degree', 'width' => '120', 'align' => 'center'],
                ['title' => '发主题者', 'field' => 'send', 'width' => '120', 'align' => 'center'],
                ['title' => '仅回复者', 'field' => 'reply', 'width' => '120', 'align' => 'center'],
                ['title' => '围观者', 'field' => 'see', 'width' => '120', 'align' => 'center'],
                ['title' => '发主题者', 'field' => 'send_one', 'width' => '120', 'align' => 'center'],
                ['title' => '仅回复者', 'field' => 'reply_one', 'width' => '120', 'align' => 'center'],
                ['title' => '围观者', 'field' => 'see_one', 'width' => '120', 'align' => 'center'],
            ],
        ],
        'click'         => [
            ['title' => '日期', 'field' => 'date', 'width' => '100', 'align' => 'center'],
            ['title' => '点击量', 'field' => 'num', 'width' => '120', 'align' => 'center'],
            ['title' => '地址', 'field' => 'url', 'width' => '1000', 'align' => 'left'],
        ],
        'tbActivity'    => [
            ['title' => '日期', 'field' => 'date', 'width' => '100', 'align' => 'center'],
            ['title' => '活动名称', 'field' => 'name', 'width' => '100', 'align' => 'center'],
            ['title' => '主题id', 'field' => 'zt_id', 'width' => '100', 'align' => 'center'],
            ['title' => '端类型', 'field' => 'type', 'width' => '120', 'align' => 'center'],
            ['title' => 'pv', 'field' => 'pv', 'width' => '120', 'align' => 'center'],
            ['title' => 'uv', 'field' => 'uv', 'width' => '120', 'align' => 'center'],
            ['title' => '登录用户数', 'field' => 'login', 'width' => '120', 'align' => 'center'],
            ['title' => '发回复贴数', 'field' => 'reply_n', 'width' => '120', 'align' => 'center'],
            ['title' => '发回复贴人数', 'field' => 'reply_n2', 'width' => '120', 'align' => 'center'],
            ['title' => '发楼中楼数', 'field' => 'send_n', 'width' => '120', 'align' => 'center'],
            ['title' => '发楼中楼人数', 'field' => 'send_n2', 'width' => '120', 'align' => 'center'],
        ],
        'baiduVisit'    => [
            ['title' => '日期', 'field' => 'date', 'width' => '100', 'align' => 'center'],
            ['title' => '端类型', 'field' => 'type', 'width' => '120', 'align' => 'center'],
            ['title' => '吧名', 'field' => 'name', 'width' => '120', 'align' => 'center'],
            ['title' => 'pv', 'field' => 'pv', 'width' => '120', 'align' => 'center'],
            ['title' => 'uv', 'field' => 'uv', 'width' => '120', 'align' => 'center'],
            ['title' => '发帖总数', 'field' => 'send_num', 'width' => '120', 'align' => 'center'],
            ['title' => '总发帖人数', 'field' => 'send_p_num', 'width' => '120', 'align' => 'center'],
            ['title' => '发主题贴数', 'field' => 'send_theme', 'width' => '120', 'align' => 'center'],
            ['title' => '发主题贴人数', 'field' => 'send_p_theme', 'width' => '120', 'align' => 'center'],
            ['title' => '发回复贴数', 'field' => 'reply_num', 'width' => '120', 'align' => 'center'],
            ['title' => '发回复贴人数', 'field' => 'reply_p_num', 'width' => '120', 'align' => 'center'],
            ['title' => '当天关注吧次数', 'field' => 'today_focus', 'width' => '120', 'align' => 'center'],
            ['title' => '签到次数', 'field' => 'signin', 'width' => '120', 'align' => 'center'],
        ],
        'pool'          => [
            ['title' => '日期', 'field' => 'date', 'width' => '100', 'align' => 'center'],
            ['title' => '剩余总数量', 'field' => 'last', 'width' => '200', 'align' => 'center'],
            ['title' => '获取总数量', 'field' => 'get', 'width' => '200', 'align' => 'center'],
            ['title' => '消耗总数量', 'field' => 'reduce', 'width' => '200', 'align' => 'center'],
        ],
        'synthesize'    => [
            ['title' => '日期', 'field' => 'date', 'width' => '100', 'align' => 'center'],
            ['title' => '剩余总数量', 'field' => 'last', 'width' => '200', 'align' => 'center'],
            ['title' => '拥有人数', 'field' => 'get', 'width' => '200', 'align' => 'center'],
            ['title' => '过期数量', 'field' => 'reduce', 'width' => '200', 'align' => 'center'],
        ],

    ],
];
